plugins {
    id "com.android.application"
}

android {
    namespace "com.longfanfanya.pomodoro.nativeapp"
    compileSdk 35

    defaultConfig {
        applicationId "com.longfanfanya.pomodoro.nativeapp"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}
